name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 'centos:latest'
    
    steps:
    - uses: actions/checkout@v2
    - name: prepare1
      run: yum -y install epel-release 
    - name: prepare2
      run: yum -y update && yum -y install cmake3 git octave wget libxml2 libxml2-devel bc
    - name: prepare3
      run: yum -y groups install "Development Tools"
    - name: prepare4
      run: yum -y install ncurses-devel readline-devel python-dateutil python-six perl-ExtUtils-ParseXS 
    - name: preparepip
      run: pip3 install -r Resources/QA/requirements.txt
    - name: qa
      run: ./QAHelper.sh -ex
