name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: 'blemming2/marte2-ci'
    
    steps:
    - name: patchgit
      run: sudo apt-get install -y software-properties-common && sudo apt-get update && sudo add-apt-repository -y ppa:git-core/ppa && sudo apt-get update && sudo apt-get install -y git
    - uses: actions/checkout@v2
    - name: preparepip
      run: pip3 install -r Resources/QA/requirements.txt
    - name: preparegit
      run: git branch --set-upstream-to=origin/master master
    - name: qa
      run: ./QAHelper.sh -ex
